/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main */

#ifndef _Included_main
#define _Included_main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main
 * Method:    pixel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_pixel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
