/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_World */

#ifndef _Included_model_World
#define _Included_model_World
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_World
 * Method:    toMatrix
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_model_World_toMatrix
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
