/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExampleObjectsJNI */

#ifndef _Included_ExampleObjectsJNI
#define _Included_ExampleObjectsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExampleObjectsJNI
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)LUserData;
 */
JNIEXPORT jobject JNICALL Java_ExampleObjectsJNI_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     ExampleObjectsJNI
 * Method:    printUserData
 * Signature: (LUserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ExampleObjectsJNI_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
